backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"
publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blogs"
    create: true
    add_to_top: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "LLL"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "products"
    label: "Products"
    folder: "content/products" 
    create: true
    add_to_top: true
    slug: "{{slug}}"
    fields:
      - {label: "Product Image", name: image, widget: image, default: "/images/placeholder-product.png"}
      - {label: "Product Name", name: "name", widget: "string"}
      - {label: "Product Company", name: "company", widget: "string"}
      - {label: "Product Link", name: "link", widget: "string"}
      - {label: "Product Category", name: "category", widget: "select", multiple: true, options: ["Ctgry 1", "Ctgry 2", "Ctgry 3"], required: false}
  - name: "content"
    label: "Content"
    editor:
      preview: false
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Page Title", name: "title", widget: "string", default: "Home"}              
          - {label: "Featured Image", name: "featuredImage", widget: "image",  default: "images/placeholder-product.png", choose_url: false}   
          - label: "Buttons"
            name: "buttons"
            widget: list
            max: 3
            min: 1
            fields:
              - { label: "Title", name: "title", widget: "string"}              
              - { label: "Link", name: "link", widget: "string"}
              - { label: "Open link in new tab?", name: "external", widget: "boolean", default: false, required: false}                                         
      - label: "About Page"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Page Title", name: "title", widget: "string", default: "Staff"}                        
          - label: "Staff Members"
            name: "staffMembers"
            widget: list            
            fields:
              - { label: "Name", name: "name", widget: "string"}              
              - { label: "Title", name: "title", widget: "string"}
              - { label: "copy", name: "copy", widget: "copy"}
              - { label: "Image", name: "image", widget: "image",  default: "images/placeholder-product.png", choose_url: false}
      - label: "Contact Info"
        name: "contact"
        file: "content/contact.md"
        fields:
          - { label: "Page Title", name: "title", widget: "string", default: "Contact"}  
          - { label: "Phone", name: "phone", widget: "string"}
          - { label: "Email", name: "email", widget: "string"}
          - label: "Socials"
            name: "socials"
            widget: list                    
            fields:
              - { label: "Platform", name: "platform", widget: "string"} 
              - { label: "Link", name: "link", widget: "string"}   
  - name: "uploads"
    label: "Uploads"
    editor:
      preview: false
    files:
      - label: "Weekly Bulletin"
        name: "bulletin"
        file: "content/bulletin.md"
        fields:         
          - label: "Prods"
            name: "prods"
            widget: list   
            add_to_top: true                 
            fields:              
              - { label: "Text", name: "text", widget: "string"} 
              - { label: "PDF Google Link", name: "link", widget: "string"}                
              - label: "Date"
                name: "date"
                widget: "datetime"
                default: ""
                date_format: "MM/DD/YYYY"
                format: "LL"
                picker_utc: false 